# We will use Ubuntu for our image
FROM ubuntu
# Updating Ubuntu packages
RUN apt-get update && yes|apt-get upgrade

ADD server.py server.py
ADD model.pickle model.pickle

#  Adding pip3
RUN apt-get -y install python3-pip

# cython is needed for some reason, scikit-learn fails
RUN pip3 install cython
RUN pip3 install scikit-learn=='0.21.3'
RUN pip3 install nltk
RUN pip3 install flask
RUN pip3 install flask_cors
RUN pip3 install waitress

CMD ["python3", "server.py"]